name: DevSecOps CI - Multi Services

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'

env:
  AWS_REGION: ap-southeast-1
  ENVIRONMENT: dev

jobs:
  build-and-secure:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - name: ui
            context: ./src/ui
            ecr_repo: devsecops-dev-ui
            gitops_image_name: retail-store-sample-ui
          - name: catalog
            context: ./src/catalog
            ecr_repo: devsecops-dev-catalog
            gitops_image_name: retail-store-sample-catalog
          - name: carts
            context: ./src/cart
            ecr_repo: devsecops-dev-carts
            gitops_image_name: retail-store-sample-cart
          - name: checkout
            context: ./src/checkout
            ecr_repo: devsecops-dev-checkout
            gitops_image_name: retail-store-sample-checkout
          - name: orders
            context: ./src/orders
            ecr_repo: devsecops-dev-orders
            gitops_image_name: retail-store-sample-orders

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '${{ matrix.service.context }}'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/${{ matrix.service.ecr_repo }}:$IMAGE_TAG ${{ matrix.service.context }}

      - name: Run Trivy vulnerability scanner on Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.login-ecr.outputs.registry }}/${{ matrix.service.ecr_repo }}:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Push to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/${{ matrix.service.ecr_repo }}:$IMAGE_TAG

      - name: Update GitOps Repository
        if: matrix.service.name == 'ui'
        env:
          GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
          IMAGE_TAG: ${{ github.sha }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ matrix.service.ecr_repo }}
        run: |
          git clone https://x-access-token:${GITOPS_TOKEN}@github.com/tehn145/devsecops-gitops-config.git
          cd devsecops-gitops-config/k8s/overlays/${ENVIRONMENT}

          sed -i "s|newTag: .*|newTag: ${IMAGE_TAG}|g" kustomization.yaml

          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add kustomization.yaml
          git diff-index --quiet HEAD || git commit -m "Auto-update UI image to tag ${IMAGE_TAG} via CI"
          git push
